### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by Volodya-B1tik** [fstl-app/fstl#116]
Hello, please tell me, is it possible to change the background color or apply some kind of texture to it? If this is done only programmatically, tell me in which part of the code to look. thanks in advance

**Comment by mkeeter** [comment]
Right now, it's only controlled programatically.

See [`background.cpp`](https://github.com/fstl-app/fstl/blob/0268e1a082791f8a55b238dc46e292434c4721ee/src/backdrop.cpp), which uses [`quad.vert`](https://github.com/fstl-app/fstl/blob/master/gl/quad.vert) and [`quad.frag`](https://github.com/fstl-app/fstl/blob/master/gl/quad.frag) respectively as vertex and fragment shaders.

**Comment by Volodya-B1tik** [comment]
Thank you very much
