### ISSUE TITLE
Failing to Run on Windows - getting "this app can't run on your PC"

### ISSUE THREAD

**Issue by Apocallur** [fstl-app/fstl#117]
Failing to Run on Windows 10 - Getting the error

"This app can't run on your PC
To find a version for your PC, check with the software publisher"

Is it intended only for Win 11?

**Comment by DeveloperPaul123** [comment]
How are you installing the app?

**Comment by Apocallur** [comment]
Found the exe after some dumbing on the github page.
Installed the app by clicking the EXE file and went normal.
It opens when I click on the application shortcut, but gives me this error when I try to right click an STL and "Open With" it shows this error

**Comment by DeveloperPaul123** [comment]
Hmm very odd indeed.

Just to clarify the steps:
- You downloaded the installer from Github (presumably on the releases page)
- `fstl` opens fine when you launch the shortcut
- Error message appears when you try to use "open with" on an STL file?

One thing to try:

- Open `fstl` like you would normally, then drag the file you want to open into the already open `fstl` window. Does the file open correctly?

**Comment by Apocallur** [comment]
IDK why exactly, it started to work normally today.
I've recently formatted the pc, maybe was a windows update that was pending or my video driver that I reinstalled yesterday.

Thanks for the help, this viewer is amazing

**Comment by DeveloperPaul123** [comment]
Glad to hear it resolved itself. Thanks!
