### ISSUE TITLE
Feature Request: Option for inverting zoom method

### ISSUE THREAD

**Issue by runxel** [fstl-app/fstl#41]
I find the current zooming method (scroll down for zoom in) highly disturbing. 😅

**Comment by DeveloperPaul123** [comment]
I assume by the issue title you would prefer to be able to scroll up to zoom in yes?

**Comment by runxel** [comment]
Yes, exactly. For me as Windows user this seems to be way more natural.

**Comment by kevinshane** [comment]
yes please!

**Comment by DeveloperPaul123** [comment]
Done in #61 Thanks @ahorn42!
