### ISSUE TITLE
Qt 5.12.x leads to blank window

### ISSUE THREAD

**Issue by dumblob** [fstl-app/fstl#46]
The newest Qt libs [seem to require](https://stackoverflow.com/a/55235823 ) `fmt.setSamples(4)` to get rid of the blank screen and error messages. With Qt 5.11.x `fstl` worked perfectly for me, but now it doesn't any more :cry:.

Could you please implement it and release a new version?

**Comment by DeveloperPaul123** [comment]
Just curious but what OS are you on?

**Comment by dumblob** [comment]
@DeveloperPaul123 Arch Linux.

**Comment by BogdanTheGeek** [comment]
It seems to work on arch if you build it from source (not from AUR).

**Comment by swiftgeek** [comment]
Works for me on arch with master and not with latest release. Probably a good sign to tag a new release :)

**Comment by DeveloperPaul123** [comment]
@swiftgeek You mean `master` of `fstl` right? Are you using the same version of Qt as indicated in the original issue comment?

**Comment by swiftgeek** [comment]
`master` of `fstl` and I had exactly the same issue on 5.13.2 with 0.9.3

**Comment by wyatt8740** [comment]
Try doing this:
`LIBGL_ALWAYS_SOFTWARE=1 ./fstl`
For whatever reason, that made it work on my (Debian) machine, although obviously I'd prefer if fstl was using my hardware.

**Comment by DeveloperPaul123** [comment]
`fstl` now requires Qt `5.14`. Can someone see if this is still an issue with that Qt version?

**Comment by dumblob** [comment]
I've just compiled and successfully tested version 0.9.4 (but I don't know, whether it's the one already depending on Qt `5.14`). I have not encoutered any issues whatsoever - thanks!

**Comment by DeveloperPaul123** [comment]
It should be a `0.95-snapshot` version I believe for the one that requires Qt `5.14`. But if the issue seems to be resolved on your end anyway, I'll go ahead and close this.
