### ISSUE TITLE
Feature request: "Surface Angle" mode draw mode

### ISSUE THREAD

**Issue by swiftgeek** [fstl-app/fstl#48]
"Surface Angle" as seen on [github/gist stl previews](https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/stl/x-carriage.stl) makes it easier for me to figure out/make out features of 3D model

**Comment by mkeeter** [comment]
Seems useful!  The mesh fragment shader is [here](https://github.com/mkeeter/fstl/blob/master/gl/mesh.frag) if you're interested in opening a PR.
