### ISSUE TITLE
Maximize window on startup

### ISSUE THREAD

**Issue by gmlewis** [fstl-app/fstl#53]
The very first thing I always do after running `fstl` is to maximize the window.

In `window.cpp`, immediately after the opening curly brace on line 17 (before the call to `setWindowTitle("fstl");`), I added this:

```
    setWindowState(Qt::WindowMaximized);
```

and now it behaves like I want.  Since this is such a simple change, I didn't write a PR.
Feel free to close if you don't think this is useful, but I really like it.

Thank you for `fstl`!!!

**Comment by DeveloperPaul123** [comment]
Perhaps this can be an option in the `fstl` toolbar. My take on this is that while you may prefer for it to start up maximized, other users will not.
