### ISSUE TITLE
building on Mac OSX: Cannot find file: ../qt/fstl.pro.

### ISSUE THREAD

**Issue by nedelec** [fstl-app/fstl#68]
Following the instruction to building on MacOS,
> qmake ../qt/fstl.pro
I get this error:
Cannot find file: ../qt/fstl.pro.

Thanks!

**Comment by mkeeter** [comment]
Ah yes, we switched to CMake.

I updated the README in 2ed355457f1dc91c87f4835d50a34d6ffbd31d6e

**Comment by nedelec** [comment]
Thank you, it worked and I could build fstl.
Is it possible to zoom in/out in fstl?

**Comment by DeveloperPaul123** [comment]
> Is it possible to zoom in/out in fstl?

Yes, on Windows it's Ctrl + Mouse Wheel scroll. Not sure what the MacOS equivalent is.
