### ISSUE TITLE
how to support gcode files

### ISSUE THREAD

**Issue by 19504643** [fstl-app/fstl#69]
Hi, this is the fastest application we have ever to open the big STL file, 
and can you support gcode file such as .g .gco .gcode
![image](https://user-images.githubusercontent.com/4372492/110411653-ec853e80-80c5-11eb-9ece-9dca21437b28.png)

**Comment by DeveloperPaul123** [comment]
I think supporting other file types is beyond the scope of this application at this time.

**Comment by 19504643** [comment]
ok, that's it, maybe there should anoter program named fgco
