### ISSUE TITLE
FSTL is not able to load stl files in a big endian environment (PowerPC)

### ISSUE THREAD

**Issue by mercurioblu** [fstl-app/fstl#72]
I would like to use FSTL on my Debian installation working on a PowerPC CPU and a 64bit linux environment.
If I try to load any STL file, FSTL does exactly nothing, it does not show any object, nor provided an alert of any kind that something went wrong. I tried recompiling from source code the current version from this repository, but again FSTL seems to ignore any STL file I select.
I might be probably wrong, but it seems to me that STL files I am trying to load with FSTL are encoded as little endian and the FSTL loader is not able to detect that it is running on a big endian system.

**Comment by DeveloperPaul123** [comment]
Would you be able to share the file that `fstl` cannot load?

**Comment by mboerwinkle** [comment]
Also, a few other things that might be interesting:
  -Can you load this ([Sphericon.stl](https://upload.wikimedia.org/wikipedia/commons/b/b1/Sphericon.stl)) ascii STL?
  -What Debian port are you using? You say it is big endian, but https://www.debian.org/ports/ only lists little endian PPC as currently supported.
Thanks,
Martin

**Comment by mkeeter** [comment]
We copy directly from the binary file into a `float` [here](https://github.com/fstl-app/fstl/blob/master/src/loader.cpp#L172).  You can try editing that line to something like

```
qFromLittleEndian<float>(b, 3, &v[i]);
```
and seeing if that fixes it.

**Comment by mercurioblu** [comment]
Here the file I am trying to load, zipped as GitHub does not allow to upload an stl file directly
[flat.zip](https://github.com/fstl-app/fstl/files/6266360/flat.zip)

**Comment by mercurioblu** [comment]
@mboerwinkle Yes, I can see the file "Sphericon.stl"
![image](https://user-images.githubusercontent.com/43654756/113753617-9203f000-970e-11eb-9a4e-cbb2a0aa8fd8.png)

The following is the dump of my /etc/apt/sources.list

<pre># Repos managed by Debian ports
deb http://ftp.ports.debian.org/debian-ports/ sid main 
deb-src http://ftp.debian.org/debian/ sid main 
deb [arch=all] http://ftp.debian.org/debian/ sid non-free contrib main 
# Repo managed by PowerProgressCommunity
deb [arch=ppc64] https://repo.powerprogress.org/debian/ sid main </pre>

**Comment by mkeeter** [comment]
Did you try the fix I suggested [here](https://github.com/fstl-app/fstl/issues/72#issuecomment-814272856)?

**Comment by mercurioblu** [comment]
@mkeeter Hurray, yes, replacing `memcpy(&v[i], b, 3*sizeof(float));` with `qFromLittleEndian<float>(b, 3, &v[i]);` in src/loader.cpp#L172 di the trick! Thank you!

![image](https://user-images.githubusercontent.com/43654756/113821117-f5783700-977b-11eb-9f8f-6a5d6d2b71a3.png)

Could you please include this fix in the main branch so that Debian will get it in their repositories?

Unfortunately I now have another issue, the file loader dialog does not show up any *.stl file as it did previously and to load files I have to launch fstl from terminal providing the filename to load.
On the image below, on left there is fstl installed from Debian repo and on the right the fstl I just compiled from sources with the patch you provided but that does not allow me to load any stl file, do you want me to open another issue about this?

![image](https://user-images.githubusercontent.com/43654756/113821369-4f78fc80-977c-11eb-901a-e8b0b8774c8d.png)

**Comment by sur5r** [comment]
The version in Debian does not yet include the fix for #59. So I think #60 is the relevant change here. I don't understand yet how it can break like that...

**Comment by mkeeter** [comment]
Okay, fixed in 843415dccdcf9d15322f84c3e4b2cbd8515283b6.

Please open another issue for the file dialog, but let me ask – what happens if you click on "STL files" in the lower-right corner of the file dialog?  If that opens a dropdown that lets you pick between "STL files" and "*.stl", then it's probably your shell (GNOME?) behaving strangely.
