### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sur5r** [fstl-app/fstl#83]
Given several features have been implemented since the 0.9.4 release, maybe it's time to add a milestone for 0.9.5 and decide which issues should be completed for it.

**Comment by DeveloperPaul123** [comment]
Yeah this is probably a good idea to get some of the new features out there to people who don't build from source. 

I think at a minimum we could version the next release `0.10.0` if not `1.0.0`. Thoughts?

**Comment by sur5r** [comment]
I'd go with `0.10.0`. For `1.0` I would like to polish some things and take care of most of the open issues.
But I don't care about the exact versioning very much. I consider frequent, incremental releases more important.

**Comment by DeveloperPaul123** [comment]
I've added a new pre-release https://github.com/fstl-app/fstl/releases/tag/v0.10.0

I would like to do some more testing and build on Linux as well before fully releasing. Should be able to do the full release soon.

**Comment by brunetton** [comment]
Just built on Ubuntu 21.10, works great

**Comment by DeveloperPaul123** [comment]
@sur5r @brunetton Would one/both of you be able to test generated rpm and deb packages? The attached zip contains both a RPM and a `.deb` package. I built them using WSL 2 on Windows.

[fstl-0.10.0.zip](https://github.com/fstl-app/fstl/files/9003750/fstl-0.10.0.zip)

**Comment by brunetton** [comment]
> @sur5r @brunetton Would one/both of you be able to test generated rpm and deb packages? The attached zip contains both a RPM and a `.deb` package. I built them using WSL 2 on Windows.
> 
> [fstl-0.10.0.zip](https://github.com/fstl-app/fstl/files/9003750/fstl-0.10.0.zip)

I can only deb package, as I'm using Ubuntu and the result is: OK, no problems here. But I probably still have all dependencies, so it's probably not a super test. It would be better to start from a fresh installation.

**Comment by sur5r** [comment]
The binary from the `.deb` works fine, but I would strongly advise against distributing that. It does not specify any dependencies which will result in odd bug reports. If you want to ship an upstream `.deb`, please have a look at the Debian packaging and use that. Maybe this could be done via GitHub actions as well.

**Comment by DeveloperPaul123** [comment]
`0.10.0` has now been released. We'll work on fixing Linux packaging in the future.
