### ISSUE TITLE
Feature Request - Quick selection of common viewpoints

### ISSUE THREAD

**Issue by pocomane** [fstl-app/fstl#94]
While using fstl to preview a model I am designing, it would be very convenient to have a way to quick select the top/botto, left/right or front/back viewpoint. A submenu in the "View" menu would be perfect.

Also an option to center the view on the object, keeping the view angle would be useful.

(I do not know if there are some "Hidden" hotkeys for such operation, but in any case I think a menu item would be an improvement)

**Comment by pocomane** [comment]
I have some [working code](https://github.com/pocomane/fstl/commit/2311e7344c12c4afab88751e3329689a5152d045) . I did not make a pull request because I am unsure about the code quality (never used qt before).

**Comment by DeveloperPaul123** [comment]
@pocomane Thanks for the code. If you file a PR we can start the formal review process and get your code merged with changes if need be.
